@extends('layouts.app')
@section('content')
@php($rows = old('items', $invoice->exists ? $invoice->items->map(fn($item) => $item->only(['item_type','description','quantity','unit_price']))->all() : [['item_type' => 'room_fee', 'description' => '', 'quantity' => 1, 'unit_price' => '']]))
<div class="actions"><h1>{{ $invoice->exists ? 'Cập nhật' : 'Tạo' }} hóa đơn</h1><a href="{{ route('invoices.index') }}">Quay lại</a></div>
<form method="post" action="{{ $invoice->exists ? route('invoices.update', $invoice) : route('invoices.store') }}">@csrf @if($invoice->exists) @method('PUT') @endif
<p><label>Hợp đồng / sinh viên / phòng <select name="contract_id" required><option value="">-- Chọn hợp đồng --</option>@foreach($contracts as $contract)<option value="{{ $contract->id }}" @selected(old('contract_id', $invoice->contract_id) == $contract->id)>{{ $contract->contract_code }} — {{ $contract->allocation->student->user->name ?? '' }} ({{ $contract->allocation->bed->room->building->code ?? '' }}-{{ $contract->allocation->bed->room->room_number ?? '' }})</option>@endforeach</select></label></p>
<p><label>Mã hóa đơn <input name="invoice_code" value="{{ old('invoice_code', $invoice->invoice_code) }}" placeholder="Để trống để tự tạo"></label></p>
<p><label>Tháng <input type="number" name="billing_month" min="1" max="12" value="{{ old('billing_month', $invoice->billing_month ?: now()->month) }}" required></label><label>Năm <input type="number" name="billing_year" min="2000" value="{{ old('billing_year', $invoice->billing_year ?: now()->year) }}" required></label><label>Hạn thanh toán <input type="date" name="due_date" value="{{ old('due_date', $invoice->due_date?->format('Y-m-d')) }}"></label></p>
<h2>Chi tiết khoản tiền</h2><p>Chọn loại khoản thu, nhập số lượng và đơn giá. Thành tiền được tính trên máy chủ.</p>
<table id="items"><thead><tr><th>Loại</th><th>Mô tả</th><th>Số lượng</th><th>Đơn giá</th><th></th></tr></thead><tbody>@foreach($rows as $index => $row)<tr><td><select name="items[{{ $index }}][item_type]" required>@foreach($itemTypes as $key => $label)<option value="{{ $key }}" @selected(($row['item_type'] ?? '') === $key)>{{ $label }}</option>@endforeach</select></td><td><input name="items[{{ $index }}][description]" value="{{ $row['description'] ?? '' }}"></td><td><input type="number" step="0.01" min="0.01" name="items[{{ $index }}][quantity]" value="{{ $row['quantity'] ?? 1 }}" required></td><td><input type="number" step="0.01" min="0" name="items[{{ $index }}][unit_price]" value="{{ $row['unit_price'] ?? '' }}" required></td><td><button type="button" onclick="this.closest('tr').remove()">Xóa</button></td></tr>@endforeach</tbody></table>
<button type="button" id="add-item">+ Thêm khoản</button><button type="submit">{{ $invoice->exists ? 'Lưu thay đổi' : 'Tạo hóa đơn' }}</button></form>
<template id="item-template"><tr><td><select name="items[__INDEX__][item_type]" required>@foreach($itemTypes as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></td><td><input name="items[__INDEX__][description]"></td><td><input type="number" step="0.01" min="0.01" name="items[__INDEX__][quantity]" value="1" required></td><td><input type="number" step="0.01" min="0" name="items[__INDEX__][unit_price]" required></td><td><button type="button" onclick="this.closest('tr').remove()">Xóa</button></td></tr></template>
<script>let nextIndex={{ count($rows) }};document.getElementById('add-item').onclick=()=>document.querySelector('#items tbody').insertAdjacentHTML('beforeend',document.getElementById('item-template').innerHTML.replaceAll('__INDEX__',nextIndex++));</script>
@endsection
